scan_timeout = 10
format = "$all"
right_format = "$directory $time"

[aws]
symbol = "[\ue7ad ](fg:#FF9900)"

[aws.region_aliases]
ap-northeast-1 = 'æ±äº¬'
us-east-1 = 'ãƒãƒ¼ã‚¸ãƒ‹ã‚¢'

[azure]
symbol = "[ó° … ](fg:#008AD7)"

[character]
error_symbol = "[ğŸ ](bold bright-red)[ï„](bold red)"
success_symbol = "[ğŸ ](bold #7faba9)[ï„](bold #7faba9)"

[cmd_duration]
min_time = 500
show_milliseconds = true
format = "ğŸ—‘ [$duration](bold #a2cc89)"

[directory]
truncation_length = 100
truncate_to_repo = false
truncation_symbol = "-"

[gcloud]
symbol = "[ \uf11f6 ](fg:#4285F4)"

[hostname]
ssh_only = false
format = "[ \ue7e6 ](bold #a0d8ef)[$hostname ]($style)"

[ruby]
symbol = "[î­ˆ ](fg:#d12e59)"

[time]
disabled = false
format = '[$time]($style)'
time_format = '%Y-%m-%d %H:%M'
utc_time_offset = '+9'

[username]
format = "[$user]($style)"
disabled = false
show_always = true
