scan_timeout = 10
format = "$all"
right_format = "$directory $time"

[aws]
symbol = "[ïƒ‚ ](fg:#FF9900)"

[aws.region_aliases]
ap-northeast-1 = 'tokyo'
us-east-1 = 'va'

[azure]
symbol = "[ó° … ](fg:#008AD7)"

[character]
error_symbol = "[ğŸ ï„](bold red)"
success_symbol = "[ğŸ ï„](bold green)"

[cmd_duration]
min_time = 500
show_milliseconds = true
format = "ğŸ—‘ [$duration](bold #a2cc89)"

[directory]
truncation_length = 100
truncate_to_repo = false
truncation_symbol = "-"

[gcloud]
symbol = "[ ğŸ‡¬ ](fg:#4285F4)"

[hostname]
ssh_only = false
format = "[ \uf31a ](bold #a0d8ef)[$hostname ]($style)"

[ruby]
symbol = "[î­ˆ ](fg:#C73C2E)"

[time]
disabled = false
format = '[$time]($style)'
time_format = '%Y-%m-%d %H:%M'
utc_time_offset = '+9'

[username]
format = "[$user]($style)"
disabled = false
show_always = true
