scan_timeout = 10
format = "$all"
right_format = "$directory $time"

[aws]
symbol = "[ÔÉÇ ](fg:#FF9900)"

[aws.region_aliases]
ap-northeast-1 = 'tokyo'
us-east-1 = 'va'

[azure]
symbol = "[Û∞†Ö ](fg:#008AD7)"

[character]
error_symbol = "[ÔÑÅ ](bold red)"
success_symbol = "[ÔÑÅ ](bold green)"

[directory]
truncation_length = 100
truncate_to_repo = false
truncation_symbol = "-"

[gcloud]
symbol = "[ üá¨ ](fg:#4285F4)"

[hostname]
ssh_only = false
format = "[ üè† ](bold)[$hostname ]($style)"

[username]
format = "[$user]($style)"
disabled = false
show_always = true

[time]
disabled = false
format = '[$time]($style)'
time_format = '%Y-%m-%d %H:%M'
utc_time_offset = '+9'

[ruby]
symbol = "[Ó≠à ](fg:#FF0000)"
